arch: mobilenet # MobileNet V1
widen_factor: 1.0
checkpoint_fp: /home/mehran/rezamarefat/YOLO_TDDFA/weights/mb1_120x120.pth
bfm_fp: /home/mehran/rezamarefat/YOLO_TDDFA/configs/bfm_noneck_v3.pkl 
size: 120
num_params: 62
